web:
  image: docker.jingzhuan.cn/web
  volumes:
    - /Users/lizefeng/Web/dev:/home/wwwroot
    - /Users/lizefeng/Web/wwwlogs:/home/wwwlogs
  ports:
    - "80:80"
  command: "/usr/bin/supervisord -c /etc/supervisord.conf"
  container_name: 'webphp5.6'
  links:
    - mysql
    - memcached
    - redis

mysql:
  image: docker.jingzhuan.cn/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: '123456'
  container_name: 'mysql_1'
  command: mysqld

memcached:
  image: docker.jingzhuan.cn/memcached
  ports:
    - "11211:11211"
  container_name: 'memcached_1'
  command: memcached

redis:
  image: docker.jingzhuan.cn/redis
  ports:
    - "6379:6379"
  container_name: 'redis_1'
