web:
  image: docker.jingzhuan.cn/web
  volumes:
    - /Users/zhaozhigang/Project/test:/home/wwwroot
    - /Users/zhaozhigang/wwwlogs:/home/wwwlogs
  ports:
    - "80:80"
  command: "/usr/bin/supervisord -c /etc/supervisord.conf"
  container_name: 'web'
  links:
    - mysql
    - memcached
    - redis
  extra_hosts:
    - "fw1.atido.com lua.atido.com fw1.atido.net:121.201.8.65"

mysql:
  image: docker.jingzhuan.cn/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: '123456'
  container_name: 'mysql'
  command: mysqld

memcached:
  image: docker.jingzhuan.cn/memcached
  ports:
    - "11211:11211"
  container_name: 'memcached'
  command: memcached

redis:
  image: docker.jingzhuan.cn/redis
  ports:
    - "6379:6379"
  container_name: 'redis'
